DECLARE
  VDESCONTO NUMBER(6,2) := 0.50;
  VCIDADE VARCHAR(30) := 'NOVO HAMBURGO';
  VCOD_ALUNO TALUNO.COD_ALUNO%TYPE :=5;
  VTOTAL NUMBER(8,2) := 1345.89;
BEGIN
  VTOTAL := Round(VTOTAL * VDESCONTO, 2);
  DBMS_OUTPUT.PUT_LINE('TOTAL: '||VTOTAL );
  VDESCONTO := 1.20;
  VCIDADE := InitCap(VCIDADE);
  Dbms_Output.PUT_LINE('CIDADE: '||VCIDADE);
  Dbms_Output.PUT_LINE('DESCONTO: '||VDESCONTO);
  Dbms_Output.PUT_LINE('CIDADE: '||VCOD_ALUNO);
END ;