VARIABLE vDESCONTO2 NUMBER

DECLARE VCOD_ALUNO NUMBER := 1;

BEGIN
 :vDESCONTO2 := 0.90;
 Dbms_Output.PUT_LINE('DESCONTO 2: '||:vDESCONTO2);

 UPDATE TContrato SET
 TOTAL = TOTAL * :vDesconto2
 WHERE COD_ALUNO = VCOD_ALUNO;

 END;


 SELECT * FROM TCONTRATO